CREATE TABLE [dbo].[Masters](
	[Id] [int] NOT NULL IDENTITY,
	[Name] [nvarchar](50) NULL,
	[Phone] [nvarchar](10) NULL,
	[WorkBegins] TIME NULL,
	[WorkEnds] TIME NULL, 
    PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
