CREATE TABLE [dbo].[Schedules](
	[Id] [int] NOT NULL,
	[WorkBegins] [time](7) NULL,
	[WorkEnds] [time](7) NULL,
 CONSTRAINT [PK_Расписание] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO